#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/common.sh"
cd "$(repo_root)"

# `just codegen`: regenerate committed generated output (CLAUDE.md §10).
#
# The package discovery is deliberately the SAME shape as check-codegen.sh's —
# a package qualifies by declaring build_runner in its own pubspec. Two recipes
# disagreeing about which packages generate code is how a file gets verified by
# one and never regenerated by the other.
#
# Failing at zero packages rather than printing "nothing to do": this recipe is
# only ever run because someone changed a model, and a silent no-op there sends
# them to commit stale generated output.

pkgs=()
while IFS= read -r pubspec; do
    grep -qE '^[[:space:]]+build_runner:' "$pubspec" || continue
    pkgs+=("$(dirname "$pubspec")")
done < <(find packages apps -mindepth 2 -maxdepth 2 -name pubspec.yaml 2>/dev/null | sort)

[ ${#pkgs[@]} -gt 0 ] || fail "no package declares build_runner — nothing to generate"

for pkg in "${pkgs[@]}"; do
    echo "codegen: $pkg"
    (cd "$pkg" && dart run build_runner build)
done
